// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowRooms.Data;

#nullable disable

namespace ShowRooms.Migrations
{
    [DbContext(typeof(ShowRoomsContext))]
    [Migration("20230104020455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShowRooms.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Interior_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Maximum_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Top_speed")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.Property<int>("number_of_seat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("ShowRooms.Models.Car_store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarID");

                    b.HasIndex("StoreID");

                    b.ToTable("Car_store");
                });

            modelBuilder.Entity("ShowRooms.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("cylinder_number")
                        .HasColumnType("real");

                    b.Property<string>("exterior_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("work_productivity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarID")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShowRooms.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("mail_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreID")
                        .IsUnique();

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("ShowRooms.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<string>("aotomotive_parts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("service_about_car")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreID")
                        .IsUnique();

                    b.ToTable("Service");
                });

            modelBuilder.Entity("ShowRooms.Models.Store", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("ShowRooms.Models.Car_store", b =>
                {
                    b.HasOne("ShowRooms.Models.Car", "Car")
                        .WithMany("Car_stores")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowRooms.Models.Store", "Store")
                        .WithMany("Car_store")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShowRooms.Models.Category", b =>
                {
                    b.HasOne("ShowRooms.Models.Car", "Car")
                        .WithOne("Category")
                        .HasForeignKey("ShowRooms.Models.Category", "CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ShowRooms.Models.Contact", b =>
                {
                    b.HasOne("ShowRooms.Models.Store", "Store")
                        .WithOne("Contacts")
                        .HasForeignKey("ShowRooms.Models.Contact", "StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShowRooms.Models.Service", b =>
                {
                    b.HasOne("ShowRooms.Models.Store", "Store")
                        .WithOne("Services")
                        .HasForeignKey("ShowRooms.Models.Service", "StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShowRooms.Models.Car", b =>
                {
                    b.Navigation("Car_stores");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShowRooms.Models.Store", b =>
                {
                    b.Navigation("Car_store");

                    b.Navigation("Contacts");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
